import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react'

export default function Home() {

  const [client, setClient] = useState('');
  const [drink, setDrink] = useState('');

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') {
      localStorage.setItem('client', `${e.target.value}`);
      setClient(e.target.value);
     fetch('http://localhost:3000/api/hello', {
        method: 'POST',
        body: JSON.stringify({client: `${e.target.value}`}),
        headers: {
          'Content-Type': 'application/json',
        }
      })
      .then(res => {
        console.log(res);
      })
      .catch(err => {
        console.log(err);
      })
    }
  }
  useEffect(() => {
    localStorage.getItem('client') ? (setClient(localStorage.getItem('client'))) : null;
  }, [client])

  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>Personal Bartender</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Happy Hour
        </h1>
        {client ? <p className={styles.description}>Hello {client}, how can I help you</p> : (
          <p className={styles.description}>
            To whom am I speaking to? <input
            placeholder="Enter Name Here"
            onKeyDown={(event) => handleKeyDown(event)}
            />
          </p>
        )}

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

        <Link href="/recommend">
          <a className={styles.card}>
            <h2>Suggestion &rarr;</h2>
            <p>Here is what I recommend</p>
          </a>
        </Link>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
